# Generated by Django 3.0.1 on 2022-11-28 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipebook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='pic',
            field=models.ImageField(default='img', upload_to=None),
            preserve_default=False,
        ),
    ]
